export const labels: Record<string, string> = {
  legacyBrand: "Επωνυμία παλαιών προτύπων (π.χ. METEORA)",
  legacyReport: "Συγκεκριμένη παλαιά αναφορά",
  postalCode: "Ταχυδρομικός κώδικας",
  tradeName: "Διακριτικός τίτλος",
  phone: "Τηλέφωνο",
  email: "Email",
  geometryKey: "Διάταξη",
  barcodeFormat: "Τύπος barcode",
  sourceId: "Ταυτότητα πηγής",
  erpCode: "Κωδικός ERP",
  secondaryCode: "Δευτερεύων κωδικός",
  barcode: "Barcode προϊόντος",
  cartonBarcode: "Barcode κιβωτίου",
  recipeCode: "Κωδικός σύστασης",
  brands: "Επωνυμίες (κωδικοί με κόμμα)",
  names: "Περιγραφές ανά γλώσσα",
  fields: "Στοιχεία προϊόντος",
  active: "Ενεργό",
  daily: "Καθημερινό",
  dailyOrder: "Σειρά καθημερινών",
  shelfLife: "Ημέρες λήξης",
  frozen: "Κατεψυγμένο",
  code: "Κωδικός",
  name: "Περιγραφή",
  family: "Οικογένεια",
  category: "Κατηγορία",
  originKey: "Κωδικός προέλευσης",
  specificationAsset: "Αρχείο τεχνικής προδιαγραφής",
  translations: "Μεταφράσεις",
  ingredients: "Συστατικά",
  allergens: "Αλλεργιογόνα",
  nutrition: "Διατροφικά στοιχεία",
  group: "Ομάδα",
  texts: "Κείμενα ανά γλώσσα",
  manufacturer: "Παρασκευαστής ανά γλώσσα",
  origins: "Προέλευση ανά γλώσσα",
  logoAsset: "Λογότυπο",
  address: "Διεύθυνση",
  vat: "ΑΦΜ",
  city: "Πόλη",
  country: "Χώρα",
  layoutProfile: "Ειδικό προφίλ διάταξης",
  complete: "Πλήρη στοιχεία",
  profile: "Προφίλ",
  widthMm: "Πλάτος (mm)",
  heightMm: "Ύψος (mm)",
  fontSize: "Μέγεθος κειμένου (pt)",
  validated: "Δοκιμασμένο και επικυρωμένο",
  validationNote: "Αποτέλεσμα φυσικής δοκιμής",
  approvalAssets: "Εικόνες σημάτων έγκρισης",
  qrPayload: "Περιεχόμενο QR",
  queue: "Όνομα ουράς Windows",
  agentId: "Βοηθός εκτύπωσης (ID)",
  dpi: "Ανάλυση DPI",
  dotsPerMm: "Κουκκίδες ανά mm",
  printableWidthMm: "Εκτυπώσιμο πλάτος (mm)",
  rotation: "Περιστροφή",
  offsetX: "Μετατόπιση X (κουκκίδες)",
  offsetY: "Μετατόπιση Y (κουκκίδες)",
  transport: "Τύπος: zpl / windows",
  headings: "Επικεφαλίδες",
};
