import { type Data } from "@/types/records";

export const defaults: Record<string, Data> = {
  template: {
    name: "",
    family: "thermal",
    profile: "small",
    geometryKey: "",
    legacyReport: "",
    barcodeFormat: "code39",
    widthMm: 100,
    heightMm: 82,
    fontSize: 7,
    validated: false,
    validationNote: "",
    approvalAssets: [],
    qrPayload: "",
  },
  printer: {
    name: "",
    queue: "",
    agentId: "00000000-0000-0000-0000-000000000000",
    transport: "windows",
    dpi: 203,
    dotsPerMm: 8,
    widthMm: 100,
    heightMm: 82,
    printableWidthMm: 100,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    validated: false,
  },
  product: {
    sourceId: "",
    erpCode: "",
    secondaryCode: "",
    barcode: "",
    cartonBarcode: "",
    recipeCode: "",
    brands: ["1"],
    names: { el: "", en: "" },
    fields: {},
    legacyProduction: {},
    active: true,
    daily: false,
    dailyOrder: 0,
    shelfLife: 0,
    frozen: false,
  },
  recipe: {
    code: "",
    name: "",
    family: "10",
    category: "",
    originKey: "",
    specificationAsset: "",
    translations: {
      el: { ingredients: "", allergens: "", nutrition: "" },
      en: { ingredients: "", allergens: "", nutrition: "" },
    },
    nutrition: {},
  },
  brand: {
    names: { el: "", en: "" },
    legacyBrand: "",
    name: "",
    group: "brand",
    texts: { el: "", en: "" },
    manufacturer: { el: "", en: "" },
    origins: {},
    logoAsset: "",
    address: "",
    vat: "",
    city: "",
    country: "",
    layoutProfile: "",
    complete: false,
  },
  customer: {
    postalCode: "",
    name: "",
    tradeName: "",
    phone: "",
    email: "",
    address: "",
    vat: "",
    city: "",
    country: "",
    texts: {},
    complete: true,
  },
  reference: {
    name: "",
    group: "",
    texts: { el: "", en: "" },
    complete: false,
  },
  language: { name: "", headings: {}, complete: false },
  vehicle: { name: "", address: "" },
  "certificate-customer": {
    name: "",
    address: "",
    vat: "",
    city: "",
    country: "",
    texts: {},
    complete: true,
  },
};
